sudo: required
dist: trusty
language: node_js
addons:
  chrome: stable
cache:
  npm: true
notifications:
  email: false
node_js: lts/*
branches:
  only:
    - master
    - /^greenkeeper/.*$/
stages:
  - test
  - name: deploy
    if: branch = master and type != pull_request
jobs:
  include:
    - stage: test
      script:
        - run-p test:ci lint build
        - npm run test:report
    # - stage: release
    #   node_js: lts/*
    #   script: skip
    #   deploy:
    #     provider: script
    #     skip_cleanup: true
    #     script:
    #       - npm run semantic-release
